### ISSUE TITLE
Mixed content in marketplace

### ISSUE THREAD

**Issue by tbozhikov** [NativeScript/marketplace-feedback#104]
Mixed Content: The page at 'https://market.nativescript.org/?tab=templates' was loaded over HTTPS, but requested an insecure image 'http://github.com/NativeScript/template-blank/blob/master/tools/assets/marketplace.png?raw=true'. This content should also be served over HTTPS.

**Comment by zbranzov** [comment]
We have to make the same fix for the badges that are not using httpS. E.g. https://uatmarket.nativescript.org/plugins/nativescript-mapbox
