### ISSUE TITLE
List UX templates in marketplace

### ISSUE THREAD

**Issue by radeva** [NativeScript/marketplace-feedback#107]
Assumptions:
- Anonymous Voting
- Form to collect info (name + email). Save data in Eloqua.
- Images in the Readme

**Comment by zbranzov** [comment]
AC:
- on Notify Me button click - https://ux.telerik.com/wireframes/NSPluginsMarketplace/#g=1&p=_n__marketplace_-_preview_template_notified
- If you click "I want this template" database votes value should be increased and UX should change to email input.
 - If already voted the user should not be able to vote again for the same item
- If already registered for notification the user should not be able to register again for the same item
- UX templates should be marked with label "Preview and Vote".
- There should be filter on the Templates page with 3 options - (All, General, HealthCare)
- Only selected category of template should be showed on filter change
- ~~Patner's template should be marked with label "Partner Demo"~~
- ~~Partner demo template should have fields to connect with the current demo provider.~~
- ??? Should we show UX template count on Authors page as part of the real templates - do whichever is easier.

**Comment by VladimirAmiorkov** [comment]
Made PRs for each template with the new keywords needed for the template to show under the according "category": https://github.com/NativeScript?utf8=%E2%9C%93&q=template&type=public&language=

Also made PR into the template guidelines for reference: https://github.com/NativeScript/nativescript-starter-kits-utils/pull/5

**Comment by DimitarTodorov** [comment]
Issue: 
- When navigate to author's detail page, a default tab is not selected. The plugins/templates tabs are grayed.

**Comment by DimitarTodorov** [comment]
All Acceptance criteria are met. The above issue is fixed.
