### ISSUE TITLE
Merge template flavors in marketplace

### ISSUE THREAD

**Issue by radeva** [NativeScript/marketplace-feedback#108]
* Assumptions:
  - List: Show only 1 template
  - On list click: Open NG by default
  - Below the title have 3 links for 3 different flavors. Click on a link, navigates to the correct flavor
* TODO:
  - Custom logic during sync
  - Visualization

**Comment by zbranzov** [comment]
- Is it expected to omit the flavors tabs when opening a template details using direct link https://uatmarket.nativescript.org/plugins/tns-template-enterprise-auth-ts ?
- COPY files command does not change on tab switch
