### ISSUE TITLE
[TBD] Playground Samples - screenshots slideshow

### ISSUE THREAD

**Issue by radeva** [NativeScript/marketplace-feedback#123]
Slideshow the screenshots provided for each sample

**Comment by VladimirAmiorkov** [comment]
AC:

- Screenshots should change automatically without being able to change them manually
- All slideshows should change simultaneously on the same interval
- Transition effect TBD
- Interval value TBD

**Comment by nsplugins** [comment]
Deprecated. We will use only the first item of the array.
