### ISSUE TITLE
Consent for Preview templates

### ISSUE THREAD

**Issue by radeva** [NativeScript/marketplace-feedback#129]
On this page: 

We need the user's consent in order to collect his email. 
Update text on the right as follows:

[With bigger font] Sign up to make sure you'll be notified, when this template becomes available.
[With smaller font] By giving us your email, you allow Progress to contact you about updates to this specific template. 

[textbox][button]

**Comment by VladimirAmiorkov** [comment]
Updated the PR with the requested changed.
