### ISSUE TITLE
Fallback to something like homepage/bugs when searching for the GitHub repository of a plugin

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/marketplace-feedback#130]
e.g. [nativescript-couchdb](https://github.com/paragasu/nativescript-couchdb) does not have [GitHub url](https://market.nativescript.org/plugins/nativescript-couchdb) although it has the repo url in the [package.json homePage propery](https://github.com/paragasu/nativescript-couchdb/blob/master/package.json#L34)

**Comment by tgpetrov** [comment]
AC:
1. Plugins like https://github.com/triniwiz/nativescript-zip/blob/master/src/package.json#L51 should have their github page extracted from homepage or bugs in package.json
2. If the homepage is not on github like https://github.com/Kinvey/nativescript-sdk/blob/master/package.json#L6 it should not be displayed in the marketplace
