### ISSUE TITLE
Playground Samples - add analytics to track user actions regarding templates and samples

### ISSUE THREAD

**Issue by radeva** [NativeScript/marketplace-feedback#131]
- clicks on the tabs
- clicks on a selected sample
- clicks on a selected template
- "notify me" with template name
- selected category
- selected framework

child of #125

**Comment by VladimirAmiorkov** [comment]
@radeva About the ""notify me" with template name" this is outside of the samples and we already have it implemented.

**Comment by VladimirAmiorkov** [comment]
AC:
## Samples
- clicks on a selected sample - {event: "virtualEvent", eventCategory: "sample", eventAction: "open-from-list-angular", eventLabel: "detecting online/offline connectivity"}
- inner tab - {event: "virtualEvent", eventCategory: "sample", eventAction: "view-list", eventLabel: "vue-all_samples"}

## Author's Samples
- clicks on a selected sample - {event: "virtualEvent", eventCategory: "sample", eventAction: "open-from-author-page-angular", eventLabel: "detecting online/offline connectivity"}

**Comment by VladimirAmiorkov** [comment]
To verify the correct format:
- Open Developer tools > Console
- write dataLayer, this contains array of all events that have been send to Google Analytics
