### ISSUE TITLE
Playground Samples - make framework in the list more visible

### ISSUE THREAD

**Issue by radeva** [NativeScript/marketplace-feedback#132]
Refer to Rob's email and Svetlio's design

child of #125

**Comment by VladimirAmiorkov** [comment]
[Uploading V2.png...]

**Comment by VladimirAmiorkov** [comment]
This is the design:
<img width="1909" alt="v2" src="https://user-images.githubusercontent.com/4989411/40919742-09dc605e-6813-11e8-96fb-a91aa684d6c1.png">

**Comment by VladimirAmiorkov** [comment]
AC: 
- When "All" Framework is selected, the author of the sample should either be:
    - The exact author - if only one author has made all of the available frameworks samples
    - "Multiple authors" - if multiple authors have made separate framework example of the sample
- Sample with only one flavour available should show the pop up with only that flavour active
- If already filtered by a framework the pop up should not appear
