### ISSUE TITLE
Dynamic Badges - pull packages and run with latest N

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/marketplace-feedback#135]
child of #121

**Comment by lini** [comment]
1. download a marketplace plugin 
1. add plugin to app (if plugin has -dev- in name, add in devDependencies)
1. build app
3.1 build app with webpack
1. deploy app on virtual device


- decide on tooling - node? 
- use latest official versions of tns-code-modules, tns-android, tns-ios, NativeScript CLI

**Comment by lini** [comment]
Discussion 6/14/2018 
Cloud builds vs local builds
Jenkins vs dedicated machine
Where to publish reports

**Comment by lini** [comment]
1. Build sample app with plugin on Android and iOS with webpack
1. Build demo app from plugin repository (if available). Execute 'plugin.build' npm command in demo app directory before building the demo app.
1. Produce output containing the version of {N} used to build, the node and npm versions and individual results for each tested plugin. Results contain build status for android/ios with webpack (true/false) and total build time for both, also build status for demo and build time for demo.

**Comment by lini** [comment]
Demo build removed due to resource constraints and since we don't need it at the moment. Only sample app with plugin with/without webpack times are uploaded into marketplace.
