### ISSUE TITLE
Introduce App Templates

### ISSUE THREAD

**Issue by radeva** [NativeScript/marketplace-feedback#14]
Present templates in a better way on the details page.

**Comment by zbranzov** [comment]
- ~~opening a 'Page Template <type>' crashes marketplace client.js:8 ERROR TypeError: Cannot read property 'npm' of undefined
    at A.getOpenAuthorEvent (client.js:515)
    at Object.l._25.e [as updateDirectives] (client.js:817)
    at Object.updateDirectives (client.js:113)~~
- ~~there is a plugin icon and link to verified doc on templates details~~
- ~~there is a  link to verified doc on templates details~~
- ~~Template Master Detail Kinvey doesn't have image on templates home page~~
- ~~There is no loading indicator if you land on templates detail and go to home~~
