### ISSUE TITLE
Suggest / Request a plugin

### ISSUE THREAD

**Issue by radeva** [NativeScript/marketplace-feedback#15]
- UX to send some text to explain that any requests for missing plugin should be added to the forum. Text will be shown when a search is done and nothing is found.
- We to create such section in the forum (jen can help here) where people can suggest their idea. 

UX: https://ux.telerik.com/wireframes/NSPluginsMarketplace/#g=1&p=_n__marketplace_-_no_results
- [NICE TO HAVE] We to integrate notifications in Slack

**Comment by lini** [comment]
Slack integration is possible through a plugin in Discourse - https://blog.discourse.org/2016/10/official-slack-integration-for-discourse/
The plugin should be installed by the forums administrator if we want to do it.
