### ISSUE TITLE
Marketplace Redesign

### ISSUE THREAD

**Issue by lini** [NativeScript/marketplace-feedback#150]

**Comment by tbozhikov** [comment]
Acceptance criteria:
- the site redesign should follow the UX wireframes at: https://ux.telerik.com/wireframes/NSPluginsMarketplace/#g=1&p=_n__marketplace_-_authors
- the header should be fixed when scrolling, like nativescript.org
- the plugin icons should be new (as per UX)
- deprecated icons should be new (as per UX)
- should adopt to different resolutions (responsiveness)

**Comment by elena-p** [comment]
https://www.screencast.com/t/ibmpGYKR 
https://www.screencast.com/t/eA6RPYUr
https://www.screencast.com/t/SKQekaZq8Ok
https://www.screencast.com/t/NkFTyW9dHxkW
https://screencast.com/t/ArKX6qxyHRw - privacy page should be centered

**Comment by zbranzov** [comment]
https://screencast.com/t/pR06kXJl1T8 the author icons are not aligned
