### ISSUE TITLE
Cards on the last row are stretched in height

### ISSUE THREAD

**Issue by DimitarTodorov** [NativeScript/marketplace-feedback#152]
The cards on the last row are stretched in height. They are longer than the other cards. There is a bigger gap between the "playground demo" button and the description of the card.

Steps to reproduce:
1. Open the Marketplace website: https://market.nativescript.org
2. Navigate to samples.
3. Choose "Vue" and "Animations".
4. Scroll down to the bottom of the page.

Here is an image describing the issue:
<img width="2143" alt="screenshot 2018-12-11 at 12 29 12" src="https://user-images.githubusercontent.com/7533292/49794533-76f06380-fd40-11e8-8b61-1780267a71f1.png">

**Comment by elena-p** [comment]
Cannot reproduce it, could you check whether the bug is fixed?
