### ISSUE TITLE
(0.5) Analytics:: Add GTM

### ISSUE THREAD

**Issue by radeva** [NativeScript/marketplace-feedback#39]

**Comment by tbozhikov** [comment]
Initial plans for tracking discussed with Angel Tsvetkov (Acceptance Criteria)

front page
- featured items in the carousel - track usage - clicks there vs clicks in the list
- track what people search the most
- track what people search and cannot find ("No plugins found!" message)
- opened plugins - verified vs non-verified
- verified plugins count trend
- Verified vs. not verified plugins definition link - how much do the people click it (header link vs carousel link vs plugin details link)

details page:
- copy btn clicks
