### ISSUE TITLE
Search in keywords by default + Allow searching in specific field like authorName.

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/marketplace-feedback#53]
Telerik UI should be shown when searching for listview (we should search in keywords)
uatmarket.nativescript.org?search=authorName:Zdravko should return all plugins created by someone with Zdravko in its authorName (same with 'description', 'keywords', 'displayName', 'name', 'isVerified', 'version')

**Comment by zbranzov** [comment]
I'm not sure whether 'isVerified' is working.
