### ISSUE TITLE
Wrong statistics about downloads

### ISSUE THREAD

**Issue by zbranzov** [NativeScript/marketplace-feedback#77]
We are currently showing wrong numbers about downloads count as we fetch outdated data from  https://npms.io/

Example: 
http://market.nativescript.org/plugins/nativescript-mapbox

https://screencast.com/t/fQwBXf7rjNY

Research http://registry.npmjs.org/nativescript-camera

**Comment by lini** [comment]
Badge in plugin description queries npm registry directly: https://api.npmjs.org/downloads/point/last-month/nativescript-mapbox
{
  "downloads": 733,
  "start": "2017-10-25",
  "end": "2017-11-23",
  "package": "nativescript-mapbox"
}

Market uses npms data, which is usually outdated - e.g. for a query made on Nov 24, data returned is from Nov 17. https://api.npms.io/v2/package/nativescript-mapbox
{
  "from": "2017-10-18T00:00:00.000Z",
  "to": "2017-11-17T00:00:00.000Z",
  "count": 957
}

We can either query data each time the plugin details are opened (faster, client-side, will not hammer npm with requests), or we can  sync data with npm directly if npms is outdated (slower sync, server-side, lots of requests to npm registry).

**Comment by radeva** [comment]
As far as I remember we have discussed to get this data from npm directly on sync.

**Comment by lini** [comment]
http://blog.npmjs.org/post/164799520460/api-rate-limiting-rolling-out
Then, as per this document, we could use bulk package requests to the downloads API for up to 128 packages at a time. This means ~15-20 requests total for the current plugin count and statistics we need (monthly, weekly, daily).

**Comment by zbranzov** [comment]
- It seems that the sync does not fix the templates statistics:
https://market.nativescript.org/plugins/tns-template-master-detail-ng
https://www.npmjs.com/package/tns-template-master-detail-ng
