### ISSUE TITLE
Author Details

### ISSUE THREAD

**Issue by nsplugins** [NativeScript/marketplace-feedback#79]
Wireframes: https://ux.telerik.com/wireframes/NSPluginsMarketplace/#g=1&p=_n__marketplace_-_author_s_plugins

- use author icon from npmjs (take it from "publisher" field in npms.io API)
   a. get from NPM (https://www.npmjs.com/package/npm-user)
- if Eddy Verbrugen is searched, all plugins that Eddy contributes to should appear, e.g. Firebase, Mapbox should appear
- Show Twitter link for the author (take it from npms.io API)
- Show GitHub link for the author (take it from repo url?)
- ? Show Facebook  of the author
- Show author badges
   a. If author has 1+ verified plugins, show the verified badge
   b. If author is expert, show expert badge
- when click Author link on plugin detals page, it shouold navigate to the Author Details page
- when on author page, show Filter by Plugins/Templates, sub-Filter by All/Verified - WON'T IMPLEMENT

? Should we have All/Verified-like filter for Templates on Search and Author Details page?
? Should we display the 4 tabs on the author details page?

**Comment by zbranzov** [comment]
- ~~author name should look like a link https://screencast.com/t/1WzWgGrYjm . Ref https://ux.telerik.com/wireframes/NSPluginsMarketplace/#g=1&p=_n__marketplace_-_plugin_details~~
- ~~Verified author's badge not centered https://screencast.com/t/pC62TJ2m792J . Maybe line-height:1.8 :)~~
- ~~https://uatmarket.nativescript.org/plugins/nativescript-localize is showing Eddy as author but it is last published by https://www.npmjs.com/package/nativescript-localize .  lfabreges published 7 days ago~~

============
- ~~search field text is cut off on Firefox https://screencast.com/t/GxMJiRhEDqsn~~
- ~~verified vs unverified link in details page takes 2 lines~~
- ~~Remove all non NS made templates~~
