### ISSUE TITLE
List top authors

### ISSUE THREAD

**Issue by radeva** [NativeScript/marketplace-feedback#85]
Top Authors in Authors page. 
Order by owned plugins count

**Comment by tbozhikov** [comment]
Issues to be fixed/clarified:

[Authors page]
- ~plugins with capital letter?~
- separator between 2x2 columns
- ~authors with 0 plugins - do not show at all~
- ~authors sorting?~

[Site Header]
- ~authors link - separate from NativeScript.org?~
- ~hasMoreItems - scrolling issue on bigger resolutions, present in Home page as well~
