### ISSUE TITLE
Introduce template guidelines

### ISSUE THREAD

**Issue by radeva** [NativeScript/marketplace-feedback#97]
Find the proper place to link to [templates guidelines](https://github.com/NativeScript/nativescript-starter-kits-utils/blob/master/docs/style-guide-app-template-ng.md) (not found message or somewhere else)

Options discussed:
- on Templates tab, show a box with proper text to be linked
- On Template details, link in the top right yellow box (currently visible only for plugin details)

UX: https://ux.telerik.com/wireframes/NSPluginsMarketplace/#g=1&p=_n__marketplace_-_home_templates

**Comment by zbranzov** [comment]
- Not whole submission card is clickable https://screencast.com/t/OPpEmO81jh . Clicking around the center does nothing.

**Comment by radeva** [comment]
@zbranzov It's fixed on UAT now.
